on:
  pull_request:
    types:
      - closed
      - opened
      - synchronize
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dump"
        env:
          DUMP: ${{ toJSON(github.event.pull_request) }}
